image: python:3.6-alpine

pages:
    stage: deploy
    script:
      - python3 -V
      - pip3 -V
      - pip3 install -r requirements.txt
      - python3 feedsreader.py
    artifacts:
        paths:
        - public
    only:
    - master
