image: python:3.6-alpine

blogroll:
    script:
      - python3 -V
      - pip3 -V
      - pip3 install -r requirements.txt
      - python3 feedsreader/core.py
    artifacts:
        paths:
        - public/
